# **Baseline for ETTh1 | Auto_ARIMA**

- ARIMA = **A**uto**R**egress**I**ve **M**oving-**A**verage
- https://en.wikipedia.org/wiki/Autoregressive_moving-average_model

In [9]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

#!pip install pmdarima              # run only the first time to install the package
from pmdarima import auto_arima
from google.colab import files

In [2]:
# Import full data set

# ETTh1_link = "ETTh1.csv"
ETTh1_link =  "https://raw.githubusercontent.com/jauric/TUB-SS-26_Deep-Learning-Time-Series/refs/heads/main/ETTh1_data/ETTh1.csv"

data_ETTh1 = pd.read_csv(ETTh1_link, sep = ",")
data_ETTh1.head()

                  date   HUFL   HULL   MUFL   MULL   LUFL   LULL         OT
0  2016-07-01 00:00:00  5.827  2.009  1.599  0.462  4.203  1.340  30.531000
1  2016-07-01 01:00:00  5.693  2.076  1.492  0.426  4.142  1.371  27.787001
2  2016-07-01 02:00:00  5.157  1.741  1.279  0.355  3.777  1.218  27.787001
3  2016-07-01 03:00:00  5.090  1.942  1.279  0.391  3.807  1.279  25.044001
4  2016-07-01 04:00:00  5.358  1.942  1.492  0.462  3.868  1.279  21.948000

In [3]:
# Auto ARIMA model for ETTh1 data set

y = data_ETTh1.set_index("date")["OT"]

model = auto_arima(
    y,
    seasonal=False,
    stepwise=True,
    suppress_warnings=True
)

forecast = model.predict(n_periods=96)
print(forecast)

2018-06-26 20:00:00    9.547417
2018-06-26 21:00:00    9.560785
2018-06-26 22:00:00    9.574515
2018-06-26 23:00:00    9.565739
2018-06-27 00:00:00    9.556127
                         ...
2018-06-30 15:00:00    9.563558
2018-06-30 16:00:00    9.563558
2018-06-30 17:00:00    9.563558
2018-06-30 18:00:00    9.563558
2018-06-30 19:00:00    9.563558
Freq: h, Length: 96, dtype: float64

In [ ]:
# Show results 

type(forecast)
forecast

2018-06-26 20:00:00    9.547417
2018-06-26 21:00:00    9.560785
2018-06-26 22:00:00    9.574515
2018-06-26 23:00:00    9.565739
2018-06-27 00:00:00    9.556127
                         ...
2018-06-30 15:00:00    9.563558
2018-06-30 16:00:00    9.563558
2018-06-30 17:00:00    9.563558
2018-06-30 18:00:00    9.563558
2018-06-30 19:00:00    9.563558
Freq: h, Length: 96, dtype: float64

In [ ]:
# Show the full forecast output without truncation, let Copilot convert it to a csv

with pd.option_context("display.max_rows", None, "display.max_columns", None):
    print(forecast)

2018-06-26 20:00:00    9.547417
2018-06-26 21:00:00    9.560785
2018-06-26 22:00:00    9.574515
2018-06-26 23:00:00    9.565739
2018-06-27 00:00:00    9.556127
2018-06-27 01:00:00    9.561874
2018-06-27 02:00:00    9.568592
2018-06-27 03:00:00    9.564840
2018-06-27 04:00:00    9.560151
2018-06-27 05:00:00    9.562593
2018-06-27 06:00:00    9.565861
2018-06-27 07:00:00    9.564277
2018-06-27 08:00:00    9.562003
2018-06-27 09:00:00    9.563026
2018-06-27 10:00:00    9.564607
2018-06-27 11:00:00    9.563949
2018-06-27 12:00:00    9.562851
2018-06-27 13:00:00    9.563272
2018-06-27 14:00:00    9.564033
2018-06-27 15:00:00    9.563765
2018-06-27 16:00:00    9.563238
2018-06-27 17:00:00    9.563408
2018-06-27 18:00:00    9.563772
2018-06-27 19:00:00    9.563666
2018-06-27 20:00:00    9.563414
2018-06-27 21:00:00    9.563480
2018-06-27 22:00:00    9.563654
2018-06-27 23:00:00    9.563613
2018-06-28 00:00:00    9.563494
2018-06-28 01:00:00    9.563518
2018-06-28 02:00:00    9.563601
2018-06-28 03:00:00    9.563586
2018-06-28 04:00:00    9.563529
2018-06-28 05:00:00    9.563538
2018-06-28 06:00:00    9.563577
2018-06-28 07:00:00    9.563572
2018-06-28 08:00:00    9.563545
2018-06-28 09:00:00    9.563548
2018-06-28 10:00:00    9.563566
2018-06-28 11:00:00    9.563565
2018-06-28 12:00:00    9.563552
2018-06-28 13:00:00    9.563553
2018-06-28 14:00:00    9.563562
2018-06-28 15:00:00    9.563561
2018-06-28 16:00:00    9.563555
2018-06-28 17:00:00    9.563555
2018-06-28 18:00:00    9.563559
2018-06-28 19:00:00    9.563560
2018-06-28 20:00:00    9.563557
2018-06-28 21:00:00    9.563557
2018-06-28 22:00:00    9.563559
2018-06-28 23:00:00    9.563559
2018-06-29 00:00:00    9.563557
2018-06-29 01:00:00    9.563557
2018-06-29 02:00:00    9.563558
2018-06-29 03:00:00    9.563558
2018-06-29 04:00:00    9.563558
2018-06-29 05:00:00    9.563558
2018-06-29 06:00:00    9.563558
2018-06-29 07:00:00    9.563558
2018-06-29 08:00:00    9.563558
2018-06-29 09:00:00    9.563558
2018-06-29 10:00:00    9.563558
2018-06-29 11:00:00    9.563558
2018-06-29 12:00:00    9.563558
2018-06-29 13:00:00    9.563558
2018-06-29 14:00:00    9.563558
2018-06-29 15:00:00    9.563558
2018-06-29 16:00:00    9.563558
2018-06-29 17:00:00    9.563558
2018-06-29 18:00:00    9.563558
2018-06-29 19:00:00    9.563558
2018-06-29 20:00:00    9.563558
2018-06-29 21:00:00    9.563558
2018-06-29 22:00:00    9.563558
2018-06-29 23:00:00    9.563558
2018-06-30 00:00:00    9.563558
2018-06-30 01:00:00    9.563558
2018-06-30 02:00:00    9.563558
2018-06-30 03:00:00    9.563558
2018-06-30 04:00:00    9.563558
2018-06-30 05:00:00    9.563558
2018-06-30 06:00:00    9.563558
2018-06-30 07:00:00    9.563558
2018-06-30 08:00:00    9.563558
2018-06-30 09:00:00    9.563558
2018-06-30 10:00:00    9.563558
2018-06-30 11:00:00    9.563558
2018-06-30 12:00:00    9.563558
2018-06-30 13:00:00    9.563558
2018-06-30 14:00:00    9.563558
2018-06-30 15:00:00    9.563558
2018-06-30 16:00:00    9.563558
2018-06-30 17:00:00    9.563558
2018-06-30 18:00:00    9.563558
2018-06-30 19:00:00    9.563558
Freq: h, dtype: float64